Repository mdn/bob, pull requests merged in 2018-05, with the labels that each got.

#35 chore(tooling): Add commitizen
  README.md
  package-lock.json
  package.json
Labels: in sprint

#51 Add build status badge to README.md
  README.md
Labels: community

#57 fix(config): Fix for changes in cosmiconfig
  lib/config.js
  package-lock.json
  package.json
Labels: bug

#58 fix(packaging): Fix syntax error in package-lock
  package-lock.json
  package.json
Labels: bug
