Repository mdn/bob, pull requests merged in 2022-05, with the labels that each got.

#782 enable exceptions flag for wasm
  editor/js/editable-wat.js
  package.json
  yarn.lock
Labels: enhancement

#789 docs: update README to reflect the current state of the project
  README.md
Labels: documentation

#793 Update auto-merge.yml
  .github/workflows/auto-merge.yml
Labels: chore

#795 chore: update publish-release workflow
  .github/workflows/publish-release.yml
Labels: chore

#800 chore: add pr-rebase-needed workflow
  .github/workflows/pr-rebase-needed.yml
Labels: chore

#797 build(deps): switch from yarn to npm
  .github/workflows/test.yml
  .gitignore
  jest-puppeteer.config.js
  package-lock.json
  yarn.lock
Labels: platform

#802 docs: update readme
  README.md
Labels: documentation
