Repository mdn/bob, pull requests merged in 2022-03, with the labels that each got.

#711 fix:release - Merge redesign changes into main
  __tests__/puppeteer-tabbed-editor.test.js
  bundles.json
  editor/css/editable-css.css
  editor/css/editable-js-and-wat.css
  editor/css/editable-js.css
  editor/css/editable-wat.css
  editor/css/editor-libs/codemirror-override.css
  editor/css/editor-libs/common.css
  editor/css/editor-libs/tabby.css
  editor/css/editor-libs/ui-fonts.css
  editor/css/libs/prism.css
  editor/css/tabbed-editor.css
  editor/js/editor-libs/events.js
  editor/js/editor-libs/template-utils.js
  editor/js/editor.js
  editor/tmpl/live-css-tmpl.html
  editor/tmpl/live-js-tmpl.html
  editor/tmpl/live-tabbed-tmpl.html
  editor/tmpl/live-wat-tmpl.html
  live-examples/fonts/Inter.var.woff2
  live-examples/fonts/Montserrat-SemiBold.woff
  live-examples/fonts/Montserrat-SemiBold.woff2
  live-examples/fonts/Montserrat-VF.woff2
  live-examples/fonts/inter-v3-latin-600.woff
  live-examples/fonts/inter-v3-latin-600.woff2
  live-examples/fonts/inter-v3-latin-regular.woff
  live-examples/fonts/inter-v3-latin-regular.woff2
Labels: maintenance

#715 chore(main): release 2.1.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#716 chore(main): release 2.1.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#717 chore(main): release 2.1.3
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#697 (fix:bug) Wasm examples, display errors in output
  editor/js/editable-wat.js
  live-examples/wat-examples/statements/loop.wat
Labels: community

#720 (fix:theme) ensure correct theme is applied onload
  editor/js/editor-libs/events.js
Labels: bug

#723 fix:editor use domcontentloaded
  editor/js/editor-libs/events.js
Labels: bug

#724 chore(main): release 2.1.4
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#726 fix:editor style cursor for light and dark modes
  editor/css/editor-libs/common.css
Labels: bug

#727 chore(main): release 2.1.5
  CHANGELOG.md
  package.json
Labels: autorelease: pending
