Repository mdn/bob, pull requests merged in 2022-04, with the labels that each got.

#736 Made wat examples fit nicely without scrollbar
  editor/css/editable-js-and-wat.css
  editor/js/editable-wat.js
  lib/processor.js
Labels: bug, community

#745 Fix object formatting
  editor/js/editor-libs/console-utils.js
Labels: community

#753 chore(main): release 2.1.6
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#760 fix:palette ~ update color palette to reflect new palette
  editor/css/editor-libs/common.css
Labels: chore

#761 chore(main): release 2.1.7
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#758 feat(editor): allow setting defaultTab in tabbed examples
  editor/js/editor.js
  editor/tmpl/live-tabbed-tmpl.html
  lib/pageBuilderUtils.js
  lib/tabbedPageBuilder.js
Labels: community

#768 chore(main): release 2.2.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending
